name: aliyun
'on': '[push]'
jobs:
  build-common:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
        env:
          MY_VAR: TODO
      - name: curl
        run: |
          curl -LJo aliyun.zip https://github.com/aliyun/aliyun-cli/releases/download/v3.0.112/aliyun-cli-windows-3.0.112-amd64.zip
