name: aliyun
on: [push]
jobs:
  macos:
    name: test
    runs-on: macos-latest
    steps:
      - name: "prepare"
        uses: actions/checkout@v2
        env:
          MY_VAR: TODO
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O aliyun.tgz https://github.com/aliyun/aliyun-cli/releases/download/v3.0.112/aliyun-cli-macosx-3.0.112-amd64.tgz
      - name: "checkFolder"
        run: |
          tar -xzvf aliyun.tgz && ls -alh
      
