name: aliyun
on: [push]
jobs:
  macos:
    name: test
    runs-on: macos-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
        env:
          MY_VAR: TODO
      - name: curl
        run:
          curl -LJo aliyun.tgz https://github.com/aliyun/aliyun-cli/releases/download/v3.0.112/aliyun-cli-macosx-3.0.112-amd64.tgz
      - name: sha256
        run:
          openssl sha256 aliyun.tgz | grep "7f1d53beccbcf7da24cd0db17fa65e81a0bdeda0f719d9df0448dde7634d3d50"
      - name: unzip
        run: |
          tar zxvf aliyun.tgz && ls
      - name: test
          ./aliyun --help | grep "Alibaba Cloud Command Line Interface Version"
  