name: aliyun
'on':
  - push
jobs:
  build-common:
    name: build-common
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: Download aliyun-cli-linux-3.0.115-amd64.tgz
        run: >-
          curl -Ljo aliyun-cli-linux-3.0.115-amd64.tgz
          https://github.com/aliyun/aliyun-cli/releases/download/v3.0.115/aliyun-cli-linux-3.0.115-amd64.tgz
      - name: Download aliyun-cli-macosx-3.0.115-amd64.tgz
        run: >-
          curl -LjO 
          https://github.com/aliyun/aliyun-cli/releases/download/v3.0.115/aliyun-cli-macosx-3.0.115-amd64.tgz
      - name: Download aliyun-cli-windows-3.0.115-amd64.zip
        run: >-
          curl -LjO 
          https://github.com/aliyun/aliyun-cli/releases/download/v3.0.115/aliyun-cli-windows-3.0.115-amd64.zip
      - name: ls
        run: ls -alh
      - name: Upload aliyun-cli-windows-3.0.115-amd64.tgz
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aliyun-cli-windows-3.0.115-amd64.tgz
          asset_name: aliyun-cli-windows-3.0.115-amd64.tgz
          tag: aliyun
          overwrite: true
      - name: Upload aliyun-cli-macosx-3.0.115-amd64.tgz
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aliyun-cli-macosx-3.0.115-amd64.tgz
          asset_name: aliyun-cli-macosx-3.0.115-amd64.tgz
          tag: aliyun
          overwrite: true
      - name: Upload aliyun-cli-windows-3.0.115-amd64.zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aliyun-cli-windows-3.0.115-amd64.zip
          asset_name: aliyun-cli-windows-3.0.115-amd64.zip
          tag: aliyun
          overwrite: true
